import bcrypt from 'bcryptjs';
import { DatabaseSchema, User, Bus, Stop, Route, RouteStop, Trip, Announcement, FeedbackItem } from './types.js';

export function getSeedData(): DatabaseSchema {
  const salt = bcrypt.genSaltSync(10);
  const adminPass = bcrypt.hashSync('gomu2026', salt);
  const driverPass = bcrypt.hashSync('Driver@123', salt);
  const studentPass = bcrypt.hashSync('Student@123', salt);
  const staffPass = bcrypt.hashSync('Staff@123', salt);

  const now = new Date().toISOString();
  const pastHour = new Date(Date.now() - 3600 * 1000).toISOString();

  // Users: 1 Admin, 3 Drivers, 10 Students, 2 Staff
  const users: User[] = [
    {
      id: 'usr_admin_1',
      name: 'TEC Transport Administrator',
      email: 'tec2026@gmail.com',
      passwordHash: adminPass,
      role: 'admin',
      collegeId: 'ADM-TEC-2026',
      phone: '+91 94431 20260',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_driver_1',
      name: 'Rajesh Kumar',
      email: 'driver.rajesh@college.edu',
      passwordHash: driverPass,
      role: 'driver',
      collegeId: 'DRV-TEC-01',
      phone: '+91 98421 99810',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_driver_2',
      name: 'Anita Sharma',
      email: 'driver.anita@college.edu',
      passwordHash: driverPass,
      role: 'driver',
      collegeId: 'DRV-TEC-02',
      phone: '+91 98421 77230',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_driver_3',
      name: 'Murugan Senthil',
      email: 'driver.murugan@college.edu',
      passwordHash: driverPass,
      role: 'driver',
      collegeId: 'DRV-TEC-03',
      phone: '+91 98421 12345',
      status: 'pending_approval',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr_student_1',
      name: 'Aarav Patel',
      email: 'student.aarav@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-001',
      phone: '+91 94421 11001',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_student_2',
      name: 'Priya Nair',
      email: 'student.priya@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-002',
      phone: '+91 94421 11002',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_student_3',
      name: 'Rohan Gupta',
      email: 'student.rohan@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-003',
      phone: '+91 94421 11003',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_student_4',
      name: 'Sneha Reddy',
      email: 'student.sneha@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-004',
      phone: '+91 94421 11004',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_student_5',
      name: 'Karan Mehra',
      email: 'student.karan@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-005',
      phone: '+91 94421 11005',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_student_6',
      name: 'Ananya Desai',
      email: 'student.ananya@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-006',
      phone: '+91 94421 11006',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_student_7',
      name: 'David Wilson',
      email: 'student.david@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-007',
      phone: '+91 94421 11007',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_student_8',
      name: 'Emily Chen',
      email: 'student.emily@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-008',
      phone: '+91 94421 11008',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_student_9',
      name: 'Mohammed Al-Mansoor',
      email: 'student.mohammed@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-009',
      phone: '+91 94421 11009',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_student_10',
      name: 'Kavita Joshi',
      email: 'student.kavita@college.edu',
      passwordHash: studentPass,
      role: 'student',
      collegeId: 'STU-TEC-2024-010',
      phone: '+91 94421 11010',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    // Staff Members
    {
      id: 'usr_staff_1',
      name: 'Dr. K. Ramanathan (HOD)',
      email: 'staff.ramanathan@college.edu',
      passwordHash: staffPass,
      role: 'staff',
      collegeId: 'STF-TEC-101',
      department: 'Computer Science & Engineering',
      phone: '+91 98421 55001',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
    {
      id: 'usr_staff_2',
      name: 'Prof. S. Meenakshi',
      email: 'staff.meenakshi@college.edu',
      passwordHash: staffPass,
      role: 'staff',
      collegeId: 'STF-TEC-102',
      department: 'Electronics & Communication',
      phone: '+91 98421 55002',
      status: 'active',
      createdAt: pastHour,
      updatedAt: now,
    },
  ];

  // 4 Fleet Buses with Tamil Nadu TN-72 plates & full Brake / Wheel condition telemetry
  const buses: Bus[] = [
    {
      id: 'bus_01',
      plateNumber: 'TN-72-AZ-2026',
      busNumber: 'Bus 01 (Thamirabharani Express)',
      capacity: 45,
      model: 'Tata Starbus Ultra EV 2024',
      status: 'active',
      condition: 'excellent',
      brakeCondition: 'excellent',
      brakePadLifePercent: 95,
      brakePressurePsi: 118,
      wheelCondition: 'excellent',
      tirePressurePsi: 112,
      tireTreadDepthMm: 9.5,
      spareWheelPresent: true,
      brakeWheelInspectionDate: '2026-10-02',
      brakeWheelInspectionNotes: 'Heavy-duty pneumatic disc brakes and regenerative braking tested. Michelin radial tubeless tyres in prime condition.',
      fuelType: 'Electric',
      fuelLevelPercent: 90,
      mileageKm: 28450,
      lastServiceDate: '2026-09-15',
      nextServiceDue: '2026-11-20',
      features: ['Air Conditioned', 'CCTV Monitored', 'Speed Governor (50 km/h)', 'First Aid Kit', 'Emergency Exit'],
      insuranceExpiry: '2027-05-15',
      fitnessCertExpiry: '2027-08-30',
      currentRouteId: 'route_tn_01',
      currentDriverId: 'usr_driver_1',
      createdAt: pastHour,
    },
    {
      id: 'bus_02',
      plateNumber: 'TN-72-BY-4512',
      busNumber: 'Bus 02 (Nellai Royal Blue)',
      capacity: 40,
      model: 'Ashok Leyland Falcon CNG 2023',
      status: 'active',
      condition: 'good',
      brakeCondition: 'good',
      brakePadLifePercent: 88,
      brakePressurePsi: 114,
      wheelCondition: 'good',
      tirePressurePsi: 108,
      tireTreadDepthMm: 8.6,
      spareWheelPresent: true,
      brakeWheelInspectionDate: '2026-10-02',
      brakeWheelInspectionNotes: 'Full dual circuit air brakes calibrated. MRF tubeless radial tyres balanced and aligned.',
      fuelType: 'CNG',
      fuelLevelPercent: 68,
      mileageKm: 46120,
      lastServiceDate: '2026-08-28',
      nextServiceDue: '2026-10-25',
      features: ['Air Conditioned', 'CCTV Monitored', 'Emergency Fire Suppression', 'First Aid Kit'],
      insuranceExpiry: '2027-03-10',
      fitnessCertExpiry: '2027-04-18',
      currentRouteId: 'route_tn_02',
      currentDriverId: 'usr_driver_2',
      createdAt: pastHour,
    },
    {
      id: 'bus_03',
      plateNumber: 'TN-72-C-8890',
      busNumber: 'Bus 03 (Thamirabarani Greenline)',
      capacity: 50,
      model: 'Eicher Skyline Pro Euro VI 2024',
      status: 'active',
      condition: 'excellent',
      brakeCondition: 'excellent',
      brakePadLifePercent: 92,
      brakePressurePsi: 116,
      wheelCondition: 'excellent',
      tirePressurePsi: 110,
      tireTreadDepthMm: 9.2,
      spareWheelPresent: true,
      brakeWheelInspectionDate: '2026-10-01',
      brakeWheelInspectionNotes: 'ABS anti-lock braking sensors verified. Apollo EnduRace radial tyres in top condition.',
      fuelType: 'Diesel',
      fuelLevelPercent: 82,
      mileageKm: 19800,
      lastServiceDate: '2026-09-02',
      nextServiceDue: '2026-12-05',
      features: ['Air Conditioned', 'CCTV Monitored', 'Wheelchair Ramp', 'First Aid Kit', 'GPS Telemetry Beacon'],
      insuranceExpiry: '2027-09-01',
      fitnessCertExpiry: '2027-11-15',
      currentRouteId: 'route_tn_03',
      createdAt: pastHour,
    },
    {
      id: 'bus_04',
      plateNumber: 'TN-72-D-1904',
      busNumber: 'Bus 04 (Tirunelveli Campus Shuttle)',
      capacity: 32,
      model: 'Force Traveller Monobus 2022',
      status: 'maintenance',
      condition: 'needs_service',
      brakeCondition: 'fair',
      brakePadLifePercent: 68,
      brakePressurePsi: 100,
      wheelCondition: 'fair',
      tirePressurePsi: 104,
      tireTreadDepthMm: 7.1,
      spareWheelPresent: true,
      brakeWheelInspectionDate: '2026-09-28',
      brakeWheelInspectionNotes: 'Front brake pads scheduled for maintenance during upcoming quarterly depot service.',
      fuelType: 'Diesel',
      fuelLevelPercent: 35,
      mileageKm: 78500,
      lastServiceDate: '2026-06-12',
      nextServiceDue: '2026-09-30 (Overdue)',
      features: ['First Aid Kit', 'Emergency Exit Door', 'Fire Extinguisher'],
      insuranceExpiry: '2027-01-15',
      fitnessCertExpiry: '2026-12-31',
      currentRouteId: 'route_tn_04',
      createdAt: pastHour,
    },
  ];

  // 12 Stops situated exclusively in Tirunelveli, Tamil Nadu
  const stops: Stop[] = [
    {
      id: 'stop_tn_01',
      name: 'Tirunelveli Junction Railway Station & Bus Terminal',
      code: 'TNJ-01',
      latitude: 8.7289,
      longitude: 77.7126,
      landmark: 'Central Railway Concourse & Madurai Road Junction',
      address: 'Railway Feeder Road, Tirunelveli Junction, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_02',
      name: 'Vannarpettai Roundana & Thamirabarani Bridge',
      code: 'VAN-02',
      latitude: 8.7225,
      longitude: 77.7285,
      landmark: 'Sulochana Mudaliar Bridge & North Bypass Crossing',
      address: 'Tiruchendur Main Rd, Vannarpettai, Tirunelveli, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_03',
      name: 'Palayamkottai Central Bus Stand & Market',
      code: 'PLK-03',
      latitude: 8.7164,
      longitude: 77.7402,
      landmark: 'Opposite St. Johns College & Market Clock Tower',
      address: 'South Car Street, Palayamkottai, Tirunelveli, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_04',
      name: 'Veinthankulam New Central Bus Stand (MGR)',
      code: 'NBS-04',
      latitude: 8.6948,
      longitude: 77.7431,
      landmark: 'Platform 1 College Transit Bay, MGR Terminal',
      address: 'Veinthankulam New Bus Stand, Tirunelveli, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_05',
      name: 'Melapalayam Roundana & Market',
      code: 'MEL-05',
      latitude: 8.6995,
      longitude: 77.7240,
      landmark: 'Melapalayam Clock Tower & Post Office Rd',
      address: 'Hameempuram Main Rd, Melapalayam, Tirunelveli, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_06',
      name: 'Pettai Industrial Estate & Bus Stand',
      code: 'PET-06',
      latitude: 8.7421,
      longitude: 77.6789,
      landmark: 'Near Pettai Industrial Park Arch',
      address: 'Cheranmahadevi Road, Pettai, Tirunelveli, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_07',
      name: 'Tirunelveli Town Arch & Nellaiappar Temple',
      code: 'TWN-07',
      latitude: 8.7305,
      longitude: 77.6980,
      landmark: 'East Car Street Nellaiappar Temple Arch',
      address: 'Swami Sannathi St, Tirunelveli Town, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_08',
      name: 'Perumalpuram & NGO Colony Junction',
      code: 'PRM-08',
      latitude: 8.7020,
      longitude: 77.7560,
      landmark: 'NGO A Colony Main Arch & Park',
      address: 'Perumalpuram Main Rd, Tirunelveli, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_09',
      name: 'Samathanapuram & Rahmath Nagar Junction',
      code: 'SAM-09',
      latitude: 8.7120,
      longitude: 77.7490,
      landmark: 'Near District Science Centre & Rahmath Arch',
      address: 'Tiruchendur Rd, Samathanapuram, Tirunelveli, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_10',
      name: 'Thachanallur Signal & Madurai Highway',
      code: 'TCH-10',
      latitude: 8.7510,
      longitude: 77.7210,
      landmark: 'Near Thachanallur Flyover & Temple Arch',
      address: 'Madurai Road NH 44, Thachanallur, Tirunelveli, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_11',
      name: 'Kokkirakulam Collectorate Complex',
      code: 'KOK-11',
      latitude: 8.7260,
      longitude: 77.7220,
      landmark: 'District Collector Office & Court Concourse',
      address: 'Collectorate Road, Kokkirakulam, Tirunelveli, Tamil Nadu',
      createdAt: pastHour,
    },
    {
      id: 'stop_tn_12',
      name: 'Thamirabharani Engineering College (TEC) Main Campus',
      code: 'TEC-12',
      latitude: 8.7180,
      longitude: 77.7850,
      landmark: 'TEC Administrative Block & Transit Bay',
      address: 'Thamirabharani Nagar, Chathirakudypu, Tirunelveli, Tamil Nadu 627351',
      createdAt: pastHour,
    },
  ];

  // 4 Dedicated Bus Routes across Tirunelveli, Tamil Nadu
  const routes: Route[] = [
    {
      id: 'route_tn_01',
      name: 'Route 1: Tirunelveli Junction - Palayamkottai - TEC Campus Express',
      routeNumber: 'TN-01',
      color: '#F59E0B', // Amber
      description: 'Connects Tirunelveli Junction Railway Station ➔ Vannarpettai ➔ Palayamkottai Market ➔ Samathanapuram ➔ Perumalpuram ➔ TEC Campus.',
      estimatedDurationMinutes: 35,
      morningStartTime: '07:45 AM',
      eveningStartTime: '05:15 PM',
      createdAt: pastHour,
    },
    {
      id: 'route_tn_02',
      name: 'Route 2: Pettai - Town Arch - TEC Campus Corridor',
      routeNumber: 'TN-02',
      color: '#3B82F6', // Blue
      description: 'Connects Pettai Industrial Estate ➔ Nellaiappar Temple Town Arch ➔ Junction ➔ Collectorate ➔ Vannarpettai ➔ TEC Campus.',
      estimatedDurationMinutes: 40,
      morningStartTime: '07:30 AM',
      eveningStartTime: '05:00 PM',
      createdAt: pastHour,
    },
    {
      id: 'route_tn_03',
      name: 'Route 3: Veinthankulam New Bus Stand - Melapalayam - TEC Line',
      routeNumber: 'TN-03',
      color: '#10B981', // Emerald
      description: 'Connects MGR New Central Bus Stand ➔ Melapalayam Clock Tower ➔ Palayamkottai ➔ Perumalpuram ➔ TEC Campus.',
      estimatedDurationMinutes: 30,
      morningStartTime: '08:00 AM',
      eveningStartTime: '05:30 PM',
      createdAt: pastHour,
    },
    {
      id: 'route_tn_04',
      name: 'Route 4: Thachanallur - Madurai Road - TEC Rapid Transit',
      routeNumber: 'TN-04',
      color: '#8B5CF6', // Purple
      description: 'Connects Thachanallur Madurai Highway ➔ Collectorate ➔ Vannarpettai ➔ Samathanapuram ➔ TEC Campus.',
      estimatedDurationMinutes: 35,
      morningStartTime: '07:40 AM',
      eveningStartTime: '05:10 PM',
      createdAt: pastHour,
    },
  ];

  // Route stops linking the Tirunelveli locations to TEC Campus
  const route_stops: RouteStop[] = [
    // Route TN-01 stops (6 stops)
    { id: 'rs_tn1_1', routeId: 'route_tn_01', stopId: 'stop_tn_01', stopOrder: 1, scheduledMinutesFromStart: 0 },
    { id: 'rs_tn1_2', routeId: 'route_tn_01', stopId: 'stop_tn_02', stopOrder: 2, scheduledMinutesFromStart: 8 },
    { id: 'rs_tn1_3', routeId: 'route_tn_01', stopId: 'stop_tn_03', stopOrder: 3, scheduledMinutesFromStart: 16 },
    { id: 'rs_tn1_4', routeId: 'route_tn_01', stopId: 'stop_tn_09', stopOrder: 4, scheduledMinutesFromStart: 22 },
    { id: 'rs_tn1_5', routeId: 'route_tn_01', stopId: 'stop_tn_08', stopOrder: 5, scheduledMinutesFromStart: 28 },
    { id: 'rs_tn1_6', routeId: 'route_tn_01', stopId: 'stop_tn_12', stopOrder: 6, scheduledMinutesFromStart: 35 },

    // Route TN-02 stops (6 stops)
    { id: 'rs_tn2_1', routeId: 'route_tn_02', stopId: 'stop_tn_06', stopOrder: 1, scheduledMinutesFromStart: 0 },
    { id: 'rs_tn2_2', routeId: 'route_tn_02', stopId: 'stop_tn_07', stopOrder: 2, scheduledMinutesFromStart: 9 },
    { id: 'rs_tn2_3', routeId: 'route_tn_02', stopId: 'stop_tn_01', stopOrder: 3, scheduledMinutesFromStart: 17 },
    { id: 'rs_tn2_4', routeId: 'route_tn_02', stopId: 'stop_tn_11', stopOrder: 4, scheduledMinutesFromStart: 24 },
    { id: 'rs_tn2_5', routeId: 'route_tn_02', stopId: 'stop_tn_02', stopOrder: 5, scheduledMinutesFromStart: 30 },
    { id: 'rs_tn2_6', routeId: 'route_tn_02', stopId: 'stop_tn_12', stopOrder: 6, scheduledMinutesFromStart: 40 },

    // Route TN-03 stops (5 stops)
    { id: 'rs_tn3_1', routeId: 'route_tn_03', stopId: 'stop_tn_04', stopOrder: 1, scheduledMinutesFromStart: 0 },
    { id: 'rs_tn3_2', routeId: 'route_tn_03', stopId: 'stop_tn_05', stopOrder: 2, scheduledMinutesFromStart: 8 },
    { id: 'rs_tn3_3', routeId: 'route_tn_03', stopId: 'stop_tn_03', stopOrder: 3, scheduledMinutesFromStart: 16 },
    { id: 'rs_tn3_4', routeId: 'route_tn_03', stopId: 'stop_tn_08', stopOrder: 4, scheduledMinutesFromStart: 23 },
    { id: 'rs_tn3_5', routeId: 'route_tn_03', stopId: 'stop_tn_12', stopOrder: 5, scheduledMinutesFromStart: 30 },

    // Route TN-04 stops (5 stops)
    { id: 'rs_tn4_1', routeId: 'route_tn_04', stopId: 'stop_tn_10', stopOrder: 1, scheduledMinutesFromStart: 0 },
    { id: 'rs_tn4_2', routeId: 'route_tn_04', stopId: 'stop_tn_11', stopOrder: 2, scheduledMinutesFromStart: 9 },
    { id: 'rs_tn4_3', routeId: 'route_tn_04', stopId: 'stop_tn_02', stopOrder: 3, scheduledMinutesFromStart: 17 },
    { id: 'rs_tn4_4', routeId: 'route_tn_04', stopId: 'stop_tn_09', stopOrder: 4, scheduledMinutesFromStart: 25 },
    { id: 'rs_tn4_5', routeId: 'route_tn_04', stopId: 'stop_tn_12', stopOrder: 5, scheduledMinutesFromStart: 35 },
  ];

  // Active trips on Tirunelveli routes
  const trips: Trip[] = [
    {
      id: 'trip_01',
      busId: 'bus_01',
      routeId: 'route_tn_01',
      driverId: 'usr_driver_1',
      status: 'in_progress',
      startTime: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      currentStopOrder: 3,
      nextStopId: 'stop_tn_09',
      occupiedSeats: 28,
      delayMinutes: 0,
      createdAt: pastHour,
    },
    {
      id: 'trip_02',
      busId: 'bus_02',
      routeId: 'route_tn_02',
      driverId: 'usr_driver_2',
      status: 'in_progress',
      startTime: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      currentStopOrder: 2,
      nextStopId: 'stop_tn_01',
      occupiedSeats: 22,
      delayMinutes: 3,
      delayReason: 'Traffic crawl near Nellaiappar Car Street',
      createdAt: pastHour,
    },
    {
      id: 'trip_03',
      busId: 'bus_03',
      routeId: 'route_tn_03',
      driverId: 'usr_driver_1',
      status: 'scheduled',
      currentStopOrder: 1,
      nextStopId: 'stop_tn_04',
      occupiedSeats: 0,
      delayMinutes: 0,
      createdAt: pastHour,
    },
  ];

  // Real Tirunelveli coordinates for live bus locations
  const locations: Record<string, any> = {
    bus_01: {
      busId: 'bus_01',
      tripId: 'trip_01',
      latitude: 8.7180,
      longitude: 77.7340,
      speed: 36,
      heading: 110,
      accuracy: 5,
      timestamp: now,
      isSimulated: true,
    },
    bus_02: {
      busId: 'bus_02',
      tripId: 'trip_02',
      latitude: 8.7330,
      longitude: 77.7010,
      speed: 28,
      heading: 95,
      accuracy: 6,
      timestamp: now,
      isSimulated: true,
    },
    bus_03: {
      busId: 'bus_03',
      tripId: 'trip_03',
      latitude: 8.6948,
      longitude: 77.7431,
      speed: 0,
      heading: 0,
      accuracy: 8,
      timestamp: now,
      isSimulated: true,
    },
  };

  const announcements: Announcement[] = [
    {
      id: 'ann_01',
      title: 'Tirunelveli Morning Shuttle Schedule Notice',
      content: 'All TEC morning shuttles from Tirunelveli Junction and Veinthankulam New Bus Stand will depart promptly at 07:45 AM. Please arrive 5 minutes early.',
      priority: 'info',
      targetType: 'all',
      createdBy: 'usr_admin_1',
      createdByName: 'TEC Transport Administrator',
      createdAt: pastHour,
    },
    {
      id: 'ann_02',
      title: 'Vannarpettai Bridge Traffic Advisory',
      content: 'Route TN-01 & TN-04 may experience 5-minute delays near Sulochana Mudaliar Bridge due to road re-surfacing work.',
      priority: 'urgent',
      targetType: 'route',
      targetId: 'route_tn_01',
      createdBy: 'usr_admin_1',
      createdByName: 'TEC Transport Administrator',
      createdAt: pastHour,
    },
  ];

  const feedback: FeedbackItem[] = [
    {
      id: 'fb_01',
      userId: 'usr_student_1',
      userName: 'Aarav Patel',
      userEmail: 'student.aarav@college.edu',
      busId: 'bus_01',
      tripId: 'trip_01',
      category: 'cleanliness',
      rating: 5,
      message: 'Bus 01 AC was functioning perfectly today and the driver was on time at Palayamkottai stop.',
      status: 'resolved',
      resolutionNotes: 'Transport team acknowledged and driver appreciated.',
      createdAt: pastHour,
      resolvedAt: now,
    },
    {
      id: 'fb_02',
      userId: 'usr_student_2',
      userName: 'Priya Nair',
      userEmail: 'student.priya@college.edu',
      busId: 'bus_02',
      category: 'late_bus',
      rating: 4,
      message: 'Slight delay near Nellaiappar temple arch due to morning market traffic.',
      status: 'pending',
      createdAt: pastHour,
    },
  ];

  const notifications = [
    {
      id: 'notif_01',
      userId: 'usr_student_1',
      title: 'Bus #01 Approaching Palayamkottai',
      message: 'Thamirabharani Express morning trip has crossed Vannarpettai and is 3 minutes away from Palayamkottai Market.',
      type: 'trip_started' as const,
      read: false,
      createdAt: now,
    },
  ];

  const favourites = [
    {
      id: 'fav_01',
      userId: 'usr_student_1',
      routeId: 'route_tn_01',
      stopId: 'stop_tn_03',
      createdAt: pastHour,
    },
    {
      id: 'fav_02',
      userId: 'usr_student_1',
      routeId: 'route_tn_01',
      stopId: 'stop_tn_02',
      createdAt: pastHour,
    },
  ];

  return {
    users,
    buses,
    stops,
    routes,
    route_stops,
    trips,
    locations,
    location_history: [],
    announcements,
    notifications,
    feedback,
    favourites,
    password_resets: [],
    settings: {
      collegeName: 'Thamirabharani Engineering College (TEC), Tirunelveli',
      demoMode: true,
      lastUpdated: now,
    },
  };
}
